version: '3'

services:

    webapp:
        build: ./webapp
        ports: 
            - "5000:5000"
        command: ./entrypoint-webapp.sh
        depends_on:
            - postgres
            - rabbitmq

    t1_beat:
        build: ./webapp
        command: celery -A webapp.pa_tasks.celery worker -l info -Q celery --hostname=t1@%h -B
        environment:
            - C_FORCE_ROOT=true        
        depends_on:
            - webapp

    t2_sync_photos:
        build: ./webapp
        command: celery -A webapp.pa_tasks.celery worker -l info -Q sync --hostname=t2@%h
        environment:
            - C_FORCE_ROOT=true
        depends_on:
            - webapp

    t3_reclassify:
        build: ./webapp
        command: celery -A webapp.pa_tasks.celery worker -l info -Q reclassify --hostname=t3@%h
        environment:
            - C_FORCE_ROOT=true
        depends_on:
            - webapp

    t4_classify:
        build: ./webapp
        command: celery -A webapp.pa_tasks.celery worker -l info -Q classify --hostname=t4@%h
        environment:
            - C_FORCE_ROOT=true
        depends_on:
            - webapp

    cnn_service:
        build: ./cnn
        restart: always
        depends_on:
            - webapp

    rabbitmq:
        image: rabbitmq:3.7.8-alpine

    postgres:
        image: postgres:11.1-alpine
        restart: always
        volumes:
            - ./volumes/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example    

