version: '3'

services:

    webapp:
        build: ./webapp
        ports: 
            - "5000:5000"
        command: ./entrypoint-webapp.sh
        depends_on:
            - postgres
            - rabbitmq

    task1_beat:
        build: ./webapp
        command: celery -A webapp.pa_tasks.celery worker -l info -Q celery --hostname=c1@%h -B
        environment:
            - C_FORCE_ROOT=true        
        depends_on:
            - webapp

    task2_sync:
        build: ./webapp
        command: celery -A webapp.pa_tasks.celery worker -l info -Q q2 --hostname=c2@%h
        environment:
            - C_FORCE_ROOT=true
        depends_on:
            - webapp
        
    task3_cnn:
        build: ./webapp
        command: celery -A webapp.pa_tasks.celery worker -l info -Q q3 --hostname=c3@%h
        environment:
            - C_FORCE_ROOT=true
        depends_on:
            - webapp

    cnn_service:
        build: ./cnn
        restart: always
        depends_on:
            - webapp

    rabbitmq:
        image: rabbitmq:3.7.8-alpine

    postgres:
        image: postgres:11.1-alpine
        restart: always
        volumes:
            - ./volumes/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example    

