"""First DB init

Revision ID: 0c6810b8e12a
Revises: 
Create Date: 2019-01-18 16:19:56.167651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6810b8e12a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ver', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    storages_table = op.create_table('storages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_path', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    users_table = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('storage_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.Column('global_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['global_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('classification_threshold', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_path', sa.String(), nullable=False),
    sa.Column('storage_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storage_user_id'], ['storage_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_path')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('longtitude', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('remote_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('revision', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos_classes',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('alg_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['alg_id'], ['algorithms.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('photo_id', 'class_id', 'alg_id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        storages_table,
        [
            {'id':1, 'name':'dropbox', 'full_path':''},
            {'id':2, 'name':'yadisk', 'full_path':''},
        ]
    )

    op.bulk_insert(
        users_table,
        [
            {'id':1, 'login':'user', 'password':'pbkdf2:sha256:50000$YN2qN13K$9903d8b7eec4a14bf0c31ee1e66e81fb84cbbd71886dd14c9c5c9aa444112e09'},
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos_classes')
    op.drop_table('photos')
    op.drop_table('folders')
    op.drop_table('user_preferences')
    op.drop_table('storage_users')
    op.drop_table('users')
    op.drop_table('storages')
    op.drop_table('classes')
    op.drop_table('algorithms')
    # ### end Alembic commands ###
