"""empty message

Revision ID: 5df0664bcbc9
Revises: 5110495eb85a
Create Date: 2019-02-06 19:17:37.112942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df0664bcbc9'
down_revision = '5110495eb85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_1', 'folders', type_='unique')
    op.drop_constraint('folders_storage_user_id_fkey', 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'storage_users', ['storage_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('photos_folder_id_fkey', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('photos_classes_photo_id_fkey', 'photos_classes', type_='foreignkey')
    op.create_foreign_key(None, 'photos_classes', 'photos', ['photo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos_classes', type_='foreignkey')
    op.create_foreign_key('photos_classes_photo_id_fkey', 'photos_classes', 'photos', ['photo_id'], ['id'])
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('photos_folder_id_fkey', 'photos', 'folders', ['folder_id'], ['id'])
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key('folders_storage_user_id_fkey', 'folders', 'storage_users', ['storage_user_id'], ['id'])
    op.create_unique_constraint('uix_1', 'folders', ['local_path', 'storage_user_id'])
    # ### end Alembic commands ###
